	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="initial-scale = 1.0,maximum-scale = 1.0" />        
        
		<link href='favicon.png' rel='shortcut icon' type='image/x-icon'/>
		<link href='favicon.png' rel='icon' type='image/x-icon'/>
		<title>Spinattic</title>

	    <!--google font-->
		<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>

		<!-- css main -->        
	    <link rel="stylesheet" type="text/css" media="screen" href="../css/mobile.css" />
	    <!-- jquery -->    
	    <script type="text/javascript" src="../js/jquery-1.9.1.min.js"></script>
	    <script type="text/javascript" src="../js/jquery.easing.1.3.js"></script>
	    <!-- jquery ui -->        
	    <script src="../js/jquery-ui.js"></script>
        
	    <script src="../js/custom_mobile.js"></script>
		<script src="../js/ajaxlike_mobile.js"></script>
		<script src="../js/ajaxscroll_mobile.js"></script>
		
			<?php if($environment=='prod'){
				require_once("../inc/ganalitycs.inc");
			}?>		
	</head>