<?

	   	$page_title = "Spinattic | Terms of services";
	   	require("inc/header.php");
	
?>
        
        <div class="wrapper wrapper-terms wrapper-home">
        	<h1 class="terms">Spinattic Terms of Service</h1>
	        		<h2>1. Acceptance of Terms</h2>
	        		<p>Spinattic llc. ("Spinattic") welcomes you. Spinattic provides to you subject of the following Terms of Service ("TOS"), which may be updated by us from time to time without notice to you. By accessing and using the Spinattic services, you accept to be bound by the terms of the TOS. In addition, when using Spinattic owned services, you and Spinattic shall be subject to any guidelines, about those services, which may be posted and modified at any time.  Spinattic may also offer other services that are governed by different Terms of Service. In those cases the other terms of service will be posted on the relevant service to which they apply. </p>   
        			<h2>2. Description of Spinattic Services.</h2>
        			<p>Spinattic provides its users access to uploading, viewing and modifying virtual reality media. Spinattic is built with the intent to help virtual reality professionals and amateurs engage and enhance their own marketing efforts as well as communicate and create with peers. You also agree that Spinattic may include advertisements and that these advertisements are necessary for Spinattic to provide its services. You also understand and agree that Spinattic send service announcements, administrative messages and the Spinattic newsletter, and that these communications are considered part of Spinattic membership and you may not be able to opt out of receiving them. Unless explicitly stated otherwise, any new features that augment or enhance the current Spinattic, shall be subject to the TOS. You are responsible for obtaining access to Spinattic, and that access may involve third-party fees (such as internet service provider or airtime charges). You are responsible for those fees, including those fees associated with display or delivery of advertisements. In addition, you must provide and are responsible for all equipment necessary to access the Spinattic.</p>
        			<p>You understand that the technical processing and transmission of the Spinattic Services, including your content, may involve (a) transmissions of various networks; and (b) changes to conform and adapt to technical requirements of connecting networks or devices.</p>
       				<h2>3. Your Registration Obligations</h2>
       				<p>Inconsideration of your use of Spinattic, you represent that you are of legal age to form a binding contract and are not a person barred from receiving Spinattic under the laws of the United States or other applicable jurisdiction. You also agree to: (a) provide true, accurate, current and complete information about yourself as prompted by the Spinattic Service's registration fields and (b) maintain and promptly update the registration data to keep it true, accurate, current and complete. If you provide any information that is untrue, not current or incomplete, or Spinattic has reasonable grounds to suspect that such information is untrue, not current or incomplete, Spinattic has the right suspend or terminate your account and refuse any and all current or future use of the Spinattic Services (or any portion thereof).</p>
					<h2>4. Member Account, Password and Security</h2>
					<p>You will create a password and account designation upon completing Spinattic’s registration process. You are responsible for maintaining the confidentiality of the password and account and are fully responsible for all the activities that occur under your password or account. You agree to immediately notify Spinattic of any unauthorized use of your password or account or any other breach of security. Spinattic cannot and will not be liable for any loss or damages arising from your failure to comply with this section 4.</p>
					<h2>5. Member Conduct</h2>
					<p>You understand that all information, data, text, software, music, sound, photographs, graphics, video, messages, tags, or other materials ("Content"), whether publicly posted or privately transmitted, are the sole responsibility of the person from whom such Content originated. This means that you, and not Spinattic, are entirely responsible for all Content that you upload, post email, transmit or otherwise make available via Spinattic. Spinattic does not control the content posted and, as such, does not guarantee the accuracy, integrity or quality of such Content. You understand that by using Spinattic, you may be exposed to Content that is offensive, indecent or objectionable. Under no circumstances will Spinattic be liable in any way for any Content, including, but not limited to, any errors or omissions in any content, or any loss or damage of any kind incurred as a result of the use of any Content posted emailed, transmitted or otherwise made available via Spinattic</p>
					<p>You agree to not use the Spinattic Services to:</p>
					<ul>
						<li>a. upload, post, email, transmit, or otherwise make available any Content that is unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, invasive of another's privacy, hateful, or racially, ethnically, or otherwise objectionable;</li>
						<li>b. harm minors in any way</li>
						<li>c. impersonate any person or entity, including, but not limited to, a Spinattic official, moderator, host, or falsely state or otherwise misrepresent your affiliation with a person or entity.</li>
						<li>d. upload, post, email, transmit, or otherwise make available any Content that you do not have a right to make available under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements);</li>
						<li>e. upload, post, email, transmit or otherwise make available any Content that infringes any patent, trademark, trade secret, copyright or other proprietary rights;</li>
						<li>f. upload, post, email, transmit or otherwise make available any unsolicited or unauthorized "junk mail," "spam," "chain letters," "pyramid schemes," or any other form of solicitation;</li>
						<li>g. upload, post, email, transmit or otherwise make available any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment;</li>
						<li>h. interfere with or disrupt Spinattic’s services or servers or networks connected to Spinattic’s services, or disobeys any requirements, procedures, policies or regulations of networks connected to the Spinattic’s services;</li>
						<li>i. intentionally or unintentionally violate any applicable local, state, national or international law including, but not limited to, regulations by the U.S. Securities and Exchange Commission, any rules of any national or other securities exchange;</li>
						<li>j. provide material support or resources (or to conceal or disguise the nature, location, source, or ownership of material support or resources) to any organization(s) designated by the United States government as a foreign terrorist organization pursuant to section 219 of the Immigration and Nationality Act;</li>
						<li>k. "stalk" or otherwise harass another; and/or</li>
						<li>l. upload, post imagery that is not considered by Spinattic to be in the realm of virtual reality content including by not limited to plain colors, abstract shapes and or designs;</li>
						<li>m. collect or store personal data about other users in connection with the prohibited conduct and activities set forth in paragraphs a through k above.</li>
					</ul>
					<p>You acknowledge, consent and agree that Spinattic may access, preserve and disclose your account information and Content if required to do so by law or in good faith belief that such access preservation or disclosure is reasonably necessary to: (i) comply with legal process; (ii) enforce the TOS; (iii) respond to claims that any Content violates the rights of third parties; (iv) respond to your requests for customer service; or (v) protect the rights, property or personal safety of Spinattic, its users and the public.</p>
					<h2>6. Special Admonitions for International Use and Export and Import Compliance</h2>
					<p>Recognizing the global nature of the Internet, you agree to comply with all local rules regarding online conduct and acceptable Content. Use of Spinattic’s services and transfer, posting and uploading of software, technology, and other technical data via Spinattic may be subject to the export and import laws of the United States and other countries. You agree to comply with all applicable export and import laws and regulations.  In particular, you represent and warrant that you (a) will not transfer software, technology, and other technical data via Spinattic’s services to export-prohibited parties or countries; (b) will not use Spinattic’s services for military, nuclear, missile, chemical or biological weaponry end uses in violation of U.S. export laws; and (c) will not transfer, upload, or post via Spinattic any software, technology or other technical data in violation of U.S. or other applicable export laws. </p>
        			<h2>7. Contributions to Spinattic</h2>
        			<p>By submitting ideas, suggestions, documents, and/or proposals "Contributions") to Spinattic  through it suggestion or feedback web pages, you acknowledge and agree that: (a) your Contributions do not contain confidential or proprietary information; (b) Spinattic is not under any obligation of confidentiality, express or implied, with , with respect to the Contributions; (c) Spinattic shall be entitled to use or disclose (or choose not to use or disclose) such Contributions for any purpose, in any way, in any media worldwide; (d) Spinattic may have something similar to the Contributions already under consideration or in development; (e) your contributions automatically become the property of Spinattic without any obligation of Spinattic to you; and (f) you are not entitled to any compensation or reimbursement of any kind  from Spinattic under any circumstances. </p>
					<h2>8. Indemnity</h2>
					<p>You agree to indemnify and hold Spinattic and its subsidiaries, affiliates, officers, agents, employees, partners and licensors harmless from any claim or demand, including reasonable attorneys' fees, made by any third party due to or arising out of Content you submit, post, transmit, modify or otherwise make available through Spinattic’s services, your use of Spinattic’s services, your connection to Spinattic’s services, your violation of the TOS, or your violation of any rights of another.</p>
					<h2>9. General Practices Regarding Use and Storage</h2>
					<p>You agree that Spinattic has no responsibility or liability for the deletion or failure to store any messages and other communications or other Content maintained or transmitted by Spinattic. You acknowledge that Spinattic reserves the right to log off accounts that are inactive for an extended period of time. You further acknowledge that Spinattic reserves the right to modify these general practices and limits from time to time.</p>
					<h2>10. Modifications to Spinattic Services</h2>
					<p>Spinattic reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, Spinattic’s services (or any part thereof) with or without notice. You agree that Spinattic shall not be liable to you or to any third party for any modification, suspension or discontinuance of Spinattic’s services (or any part thereof).</p>
					<h2>11. Termination</h2>
					<p>You agree that Spinattic may, without prior notice, immediately terminate, limit your access to or suspend your account, and access to Spinattic. Cause for such termination, limitation of access or suspension shall include, but not be limited to, (a) breaches or violations of the TOS or other incorporated agreements or guidelines, (b)requests by law enforcement or other government agencies, (c) discontinuance or material modification to Spinattic’s services (or any part thereof), (d) unexpected technical or security issues or problems, (e) extended periods of inactivity, (f) engagement by you in fraudulent or illegal activities, and/or (g) nonpayment of any fees owed by you in connection with Spinattic’s services. Further, you agree that all terminations, limitations of access and suspensions for cause shall be made in Spinattic's sole discretion and that Spinattic shall not be liable to you or any third party for any termination of your account or access to Spinattic.</p>
					<p>Termination of your Spinattic account includes any or all of the following: (a) removal of access to all or part of the offerings within Spinattic, (b) deletion of your password and all related information, files and content associated with or inside your account (or any part thereof), and (c) barring of further use of all or part of Spinattic.</p>
					<h2>12. Dealings with Advertisers</h2>
					<p>Your correspondence or business dealings with, or participation in promotions of, advertisers found on or through Spinattic’s services, including payment and delivery of related goods or services, and any other terms, conditions, warranties or representations associated with such dealings, are solely between you and such advertiser. You agree that Spinttic shall not be responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or as the result of the presence of such advertisers on Spinattic’s services.</p>
					<h2>13. Links</h2>
					<p>Spinattic’s services may provide, or third parties may provide, links to other World Wide Web sites or resources. You acknowledge and agree that Spinattic is not responsible for the availability of such external sites or resources, and does not endorse and is not responsible or liable for any Content, advertising, products or other materials on or available from such sites or resources. You further acknowledge and agree that Spinattic shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with use of or reliance on any such Content, goods or services available on or through any such site or resource.</p>
					<h2>14. Spinattic's Proprietary Rights</h2>
					<p>You acknowledge and agree that Spinattic’s services and any necessary software used in connection with Spinattic’s services ("Software") contain proprietary and confidential information that is protected by applicable intellectual property and other laws. You further acknowledge and agree that Content contained in advertisements or information presented to you through Spinattic’s services or by advertisers is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws. Except as expressly permitted by applicable law or as authorized by Spinattic or the applicable licensor (such as an advertiser), you agree not to modify, rent, lease, loan, sell, distribute, transmit, broadcast, publicly perform or create derivative works based on Spinattic’s services, such Content or the Software, in whole or in part.</p>
					<h2>15. Disclaimer of Warranties</h2>
					<p>YOU EXPRESSLY UNDERSTAND AND AGREE THAT:</p>
					<ul>
						<li>a. YOUR USE OF THE SPINATTIC SERVICES AND SOFTWARE ARE AT YOUR SOLE RISK. SPINATTIC AND SOFTWARE ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS. SPINATTIC AND ITS SUBSIDIARIES, AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS AND LICENSORS EXPRESSLY DISCLAIM ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.</li>
						<li>b. SPINATTIC AND ITS SUBSIDIARIES, AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS AND LICENSORS MAKE NO WARRANTY THAT (i) THE SPINATTIC SERVICES OR SOFTWARE WILL MEET YOUR REQUIREMENTS; (ii) THE SPINATTIC SERVICES OR SOFTWARE WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE; (iii) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF SPINATTIC’S SERVICES OR SOFTWARE WILL BE ACCURATE OR RELIABLE; (iv) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH SPINATTIC’S SERVICES OR SOFTWARE WILL MEET YOUR EXPECTATIONS; AND (v) ANY ERRORS IN THE SOFTWARE WILL BE CORRECTED.</li>
						<li>c. ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF SPINATTIC’S SERVICES OR SOFTWARE IS ACCESSED AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR AND HEREBY WAIVE ANY AND ALL CLAIMS AND CAUSES OF ACTION WITH RESPECT TO ANY DAMAGE TO YOUR COMPUTER SYSTEM, INTERNET ACCESS, DOWNLOAD OR DISPLAY DEVICE, OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.</li>
					</ul>
					<h2>16. Limitations of Liability</h2>
					<p>YOU AGREE THAT SPINATTIC AND ITS SUBSIDIARIES, AFFILIATES, OFFICERS, EMPLOYEES, AGENTS, PARTNERS AND LICENSORS SHALL NOT BE LIABLE TO YOU FOR ANY PUNITIVE, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING, BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF SPINATTIC HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM: (a) THE USE OR THE INABILITY TO USE THE SPINATTIC SERVICE; (b) THE COST OF PROCUREMENT OF SUBSTITUTE GOODS AND SERVICES; (c) UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; (d) STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE SPINATTIC SERVICE; OR (e) ANY OTHER MATTER RELATING TO THE SPINATTIC SERVICE.</p>
					<h2>17. No Third-Party Beneficiaries</h2>
					<p>You agree that, except as otherwise expressly provided in this TOS, there shall be no third-party beneficiaries to this agreement.</p>
					<h2>18. General Information</h2>
					<p>Waiver and Severability of Terms. The failure of Spinattic to exercise or enforce any right or provision of the TOS shall not constitute a waiver of such right or provision. If any provision of the TOS is found by a court of competent jurisdiction to be invalid, the parties nevertheless agree that the court should endeavor to give effect to the parties' intentions as reflected in the provision, and the other provisions of the TOS remain in full force and effect.</p>
					<p>No Right of Survivorship and Non-Transferability. You agree that your Spinattic account is non-transferable and any rights to your Spinattic ID or contents within your account terminate upon your death. Upon receipt of a copy of a death certificate, your account may be terminated and all contents therein permanently deleted.</p>
					<p>Statute of Limitations. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of or related to use of Spinattic’S services or the TOS must be filed within one (1) year after such claim or cause of action arose or be forever barred.</p>
					<p>The section titles in the TOS are for convenience only and have no legal or contractual effect.</p>
					<h2>19. Violations</h2>
					<p>Please report any violations of the TOS to our <a href="#">Customer Care</a> group.</p>



        </div>
    <?php require_once("inc/footer.php");?>
</html>
